### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by teiminryu** [danini/stereoglue#1]
Dear developers, I am very interesting in StereoGlue and trying to compiling it for image matching. However, I encountered this error message:

**fatal error: estimators/solver_homography_one_affine_approximate.h: No such file or directory
          7 | #include "estimators/solver_homography_one_affine_approximate.h"
            |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.**

Could you kindly provide this missing file so that I can try StereoGlue? Thank you in advance.

**Comment by aloksmx** [comment]
Hi, There is one more file missing, I think:
https://github.com/danini/stereoglue/blob/main/examples/functions.py#L24
Thank you!

**Comment by danini** [comment]
This should be good now. It was a leftover from a new version that I will finish after CVPR deadline :)
