### ISSUE TITLE
How to download weight file? _0621_092607_resnet18_ori36_sca13_branchsca-best_model.pt

### ISSUE THREAD

**Issue by Dawars** [danini/stereoglue#3]
When running the example notebook _example_fundamental_matrix_fitting.ipynb_ **SuperPointWithAffNetScaleNetKornia** tries to load the model file "_0621_092607_resnet18_ori36_sca13_branchsca-best_model.pt"
https://github.com/danini/stereoglue/blob/main/examples/functions.py#L24

How can I obtain this?

**Comment by Dawars** [comment]
Found it:
https://github.com/bluedream1121/self-sca-ori/tree/main/trained_models

**Comment by ducha-aiki** [comment]
Yes, sorry for that, added a comment into the code
