### ISSUE TITLE
pystereoglue import error

### ISSUE THREAD

**Issue by teiminryu** [danini/stereoglue#6]
Hi, after successfully installing stereoglue, I have this error when importing **_pystereoglue_**. Could you please kindly let me know how to solve this issue? Thank you so much in advance. 

_pystereoglue.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z25estimateHomographyGravityRKN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEES3_S3_S3_RKNS0_IdLi3ELi3ELi0ELi3ELi3EEES6_RKSt6vectorIdSaIdEES6_S6_RN10stereoglue14RANSACSettingsE_

**Comment by danini** [comment]
This should be good now.
