### ISSUE TITLE
Missing feature trained model

### ISSUE THREAD

**Issue by teiminryu** [danini/stereoglue#7]
Dear Daniel, thank you so much for addressing the error I faced. When I try to download the feature trained model from https://github.com/bluedream1121/self-sca-ori/tree/main/trained_models, the model **__0621_092607_resnet18_ori36_sca13_branchsca-best_model.pt_**  you assigned was removed in the original GitHub repo. It looks like that authors replaced two independent trained orientation and scale models. 
Therefore, the detector **_SuperPointWithAffNetScaleNetKornia_** cannot successfully access the trained model.
Do you have any solution to this issue? Thank you for your help again.

**Comment by danini** [comment]
Here is the link: https://polybox.ethz.ch/index.php/s/BZSC37iIS1jF4A6
I added it also to the readme.
